interpreter: lexer.c parser.c REPL.c eval.c stb_ds.h env.c core.c
	cc lexer.c parser.c REPL.c eval.c env.c core.c -o repl -ggdb -std=c99


stb_ds.h:
	wget https://raw.githubusercontent.com/nothings/stb/refs/heads/master/stb_ds.h

